export * from "./detailsFilm.slice";
export * from "./genres.slice";
export * from "./movieSlice";
export * from "./nowPlayingMovies.slice";
export * from "./popularMovies.slice";
export * from "./searchMovies.slice";
export * from "./themeToggleSlice";
export * from "./topRatedMovie.slice.";
export * from "./upcomingMovies.slice";
export * from "./tv.slice"
export * from "./moviesByGenres.slice"