export * from "./Home/Home.page";
export * from "./Movie.page";
export * from "./MyProfile.page";
export * from "./NotFound.page";
export * from "./Popular.page";
export * from "./NowPlaying.page";
export * from "./TopRated.page";
export * from "./TV.page";
export * from "./Upcoming.page";
export * from "./MovieDetails.page";
export * from "./MoviesByGenres.page"